<?php

namespace SocialPro\ProjectBundle\Repository;

/**
 * CommProjectLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommProjectLikeRepository extends \Doctrine\ORM\EntityRepository
{
}
