<?php

namespace SocialPro\ProjectBundle\Repository;

/**
 * CommProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
