<?php

namespace SocialPro\ProjectBundle\Repository;

/**
 * ProjectLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectLikeRepository extends \Doctrine\ORM\EntityRepository
{
}
