<?php

namespace SocialPro\ProjectBundle\Repository;

/**
 * TrackProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
